### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Vipul-Cariappa** [Vipul-Cariappa/coder#6]
With info for developers as well as users.
And link to the actual site.

- [ ] Info for Users
- [ ] Info for developers
- [ ] Update repo description, and provide a link

**Comment by anubhav1206** [comment]
Can I get assigned?

**Comment by Vipul-Cariappa** [comment]
You can work on this. No issues. I will not assign it here. But you can work on it and open a PR. I will definitely merge it.

I have temporarily deployed the site here https://code.vipulcariappa.xyz/ . Check it out. I will change the site address (Domain Name / URL) in a few days.

I am a student and waiting for my pocket money.

**Comment by Vipul-Cariappa** [comment]
@anubhav1206  To successfully close this Issue, you only need to update the `README.md`. Short description of the Web Application and a Short description to help new developers set up their development environment to contribute.

Also, add your Name and GitHub username to the `CONTRIBUTORS.md`
